import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

const inter = Inter({ subsets: ['latin'] })
import io from "socket.io-client"
let socket=io("ws://localhost:8800")
export default function Home() {
  const [name, setName] = useState()
  const [post,setPost]=useState()
 useEffect(() => {
  socket.emit("hi", { post: name });
  socket.on("asik", (data) => {
    console.log(data);
    setPost(data);
  });
 }, [socket,name])
 
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <h1>
          <li>{post && post.post}</li>
        </h1>
        <form>
          <input
            onChange={(e) => setName(e.target.value)}
            name="name"
            value={name}
            placeholder="Enter name"
          />
          <button type="submit">submit</button>
        </form>
      </div>
    </>
  );
}
