const TestimonialApi = [
  {
    id: 1,
    image: "/man.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatment. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris",
  },
  {
    id: 2,
    image: "/computer.png",
    design: "John Doe",
    name: "Davei Luace",
    offcer: "Chief Operating Manager",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "When managment is so important. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 3,
    image: "/meet.png",
    design: "Rainbow-Themes",
    name: "Nevine Acotanza",
    offcer: "Chief Operating Officer",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "Maecenas finibus nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 4,
    image: "/blog.png",
    design: "Bound - Trolola",
    name: "Jone Duone Joe",
    offcer: "Operating Officer",
    post: "Web App Development",
    date: "Upwork - Mar 4, 2016 - Aug 30, 2021",
    desc: "Important fact to nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 5,
    image: "/blog1.png",
    design: "Glassfisom",
    name: "Nevine Dhawan",
    offcer: "CEO Of Officer",
    post: "Android App Design",
    date: "Fiver - Mar 4, 2015 - Aug 30, 2021",
    desc: "No more question for design. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris	.",
  },
  {
    id: 6,
    image: "/man.png",
    design: "NCD - DESIGN",
    name: "Mevine Thoda",
    offcer: "Marketing Officer",
    post: "CEO - Marketing",
    date: "Thoda Department - Mar 4, 2018 - Aug 30, 2021",
    desc: "Marcent Of Vanice and treatment. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris",
  },
  {
    id: 7,
    image: "/computer.png",
    design: "John Abraham",
    name: "Davei Luace",
    offcer: "Chief Operating Manager",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "When managment is so important. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 8,
    image: "/meet.png",
    design: "Rainbow-Themes",
    name: "Nevine Acotanza",
    offcer: "Chief Operating Officer",
    post: "Android App Development",
    date: "via Upwork - Mar 4, 2015 - Aug 30, 2021",
    desc: "Maecenas finibus nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 9,
    image: "/blog.png",
    design: "Bound - Trolola",
    name: "Jone Duone Joe",
    offcer: "Operating Officer",
    post: "Web App Development",
    date: "Upwork - Mar 4, 2016 - Aug 30, 2021",
    desc: "Important fact to nec sem ut imperdiet. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris.",
  },
  {
    id: 10,
    image: "/blog1.png",
    design: "Glassfisom",
    name: "Nevine Dhawan",
    offcer: "CEO Of Officer",
    post: "Android App Design",
    date: "Fiver - Mar 4, 2015 - Aug 30, 2021",
    desc: "No more question for design. Ut tincidunt est ac dolor aliquam sodales. Phasellus sed mauris hendrerit, laoreet sem in, lobortis mauris hendrerit ante. Ut tincidunt est ac dolor aliquam sodales phasellus smauris	.",
  },
];

export default TestimonialApi;
