export const offerData = [
  {
    sell: 23030,
    title: "Html",
    company_name: "Website Design",
    s1: "Professional Website Design",
    s2: "Custom Website Design",
    s3: "Responsive Website Design",
    s4: "WordPress Website Design",
    s5: "Landing Page Design",
    s6: "eCommerce Website Design",
    s7: "Website Maintenance and Support",
    s8: "Website Redesign",
    s9: "24/online Support",
    s10: "Friendly Contact",
    icon: "/webdesign.png",
    iconBg: "#383E56",
    date: "March 2020 - April 2021",
    points: [
      "Designing visually appealing and user-friendly websites using HTML, CSS, and JavaScript.",
      "Maintaining open and friendly communication for effective project collaboration.",
    ],
  },
  {
    sell: 25980,
    title: "Css/Bootstrap",
    company_name: "Website Development",
    s1: "Full Stack Web Developer for Dynamic Websites",
    s2: "E-commerce Website Development by Pro Developer",
    s3: "API Integration and Web Services Development",
    s4: "Website Development With NextJs",
    s5: "Expert Web Developer for Custom Websites",
    s6: "Web application development with Node.js",
    s7: "Website Maintenance and Support",
    s8: "Custom Web Applications Development by Pro Developer",
    s9: "24/online Support",
    s10: "Friendly Contact",
    icon: "/webdev.png",
    iconBg: "#E6DEDD",
    date: "March 2020 - April 2021",
    points: [
      "Full-stack web development expertise for creating dynamic and interactive websites.",
      "Specializing in e-commerce website development with a focus on user experience.",
    ],
  },
  {
    sell: 28700,
    title: "Tailwind Css",
    company_name: "Next.Js | Node.Js | React.Js | and MERN stack development",
    s1: "I will create a responsive website using Next.js",
    s2: "I will build a custom e-commerce platform with Next.js",
    s3: "Responsive Website Design",
    s4: "WordPress Website Design",
    s5: "I will create a blog using Next.js and integrate with a CMS",
    s6: "I will optimize your existing Next.js website for speed and performance",
    s7: "Website Maintenance and Support",
    s8: "I will develop a server-side rendered web application using Next.js",
    s9: "24/online Support",
    s10: "Friendly Contact",
    icon: "/next2.png",
    iconBg: "#E6DEDD",
    date: "March 2020 - April 2021",
    points: [
      "Creating responsive websites using Next.js for optimal user experience.",

      "Designing visually appealing and user-friendly online shopping websites with responsive layouts.",
    ],
  },
  {
    sell: 32846,
    title: "Javascript",
    company_name: "MERN Stack Developer: End-to-End Web Development Solutions",
    s1: "Full-stack MERN web development",
    s2: "Building a RESTful API using Node.js and MongoDB",
    s3: "Integration of React.js with MongoDB and Node.js",
    s4: "Customized MERN-based e-commerce website development",
    s5: "MERN-based social media platform development",
    s6: "Developing a real-time chat application using MERN stack",
    s7: "Website Maintenance and Support",
    s8: "MERN-based blog website development",
    s9: "MERN-based web application development with user authentication and authorization",
    s10: "MERN-based responsive website development for mobile devices.",
    icon: "/next1.png",
    iconBg: "#383E56",
    date: "March 2020 - Running",
    points: [
      "Building robust RESTful APIs using Node.js and MongoDB for seamless data flow.",
      "Integrating React.js with MongoDB and Node.js for efficient data handling.",
    ],
  },
  {
    sell: 45290,
    title: "React Js",
    company_name:
      "Next.js | Socket.Io Development: Build Fast, SEO-Friendly Websites And Real Time Chat Application",
    s1: "Build a Responsive React/Next.js Web App",
    s2: "Develop a Custom React/Next.js Component",
    s3: "Create a Scalable React/Next.js Website",
    s4: "Design and Develop a Landing Page with React/Next.js",
    s5: "Develop a Serverless React/Next.js Web Application",
    s6: "Optimize React/Next.js Website for Better Performance",
    s7: "Integrate APIs into React/Next.js Web App",
    s8: "Develop a Full-stack React/Next.js Web App with Authentication",
    s9: "24/online Support",
    s10: "Friendly Contact",
    icon: "/react1.png",
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present",
    points: [
      "Creating scalable Socket.Io | Next.js websites for seamless growth and expansion.",
      "Designing and developing engaging Chat Application  with Next.js and Socket.Io for user interaction.",
    ],
  },
  {
    sell: 78350,
    title: "Node Js",
    company_name: "Custom Website Design | Development And Fix Errors.",
    s1: "Fix React/Next.js Bugs and Issues",
    s2: "Fix Mern Websites Bugs and Issues",
    s3: "Website Speed Optimization",
    s4: "Responsive Web Design and Development Services",
    s5: "Customized Website Design and Development Solutions",
    s6: "eCommerce Website Design/Devlopment",
    s7: "Website Maintenance and Support",
    s8: "Custom Web Development and Error Resolution",
    s9: "24/online Support",
    s10: "Friendly Contact",
    icon: "/react2.png",
    iconBg: "#383E56",
    date: "Jan 2022 - Jan 2023",
    points: [
      "Providing 24/7 online support for immediate issue resolution and client assistance.",
      "Maintaining open and friendly communication for effective project management.",
    ],
  },
];
